#!/usr/bin/env bash
# Experimental: build atc as a GraalVM native image (see doc/development.md,
# "Native image"). The REPL defines the agent's classes at run time, which needs
# GraalVM's early runtime class loading (GraalVM CE/Oracle 25.3 or newer).
#
#   ./mill dist
#   GRAALVM_HOME=/path/to/graalvm-25.3 native/build.sh
#   out/native/atc -Djava.home="$GRAALVM_HOME" -Datc.lib.classpath=out/dist.dest/atc-lib.jar ...
#
# The binary still needs a JDK 17+ at run time, named by -Djava.home: the compiler
# reads the JDK's class metadata from its jrt: file system, and runtime class
# loading falls back to it for JDK classes the image does not carry.
# Environment: ATC_NATIVE_XMX (builder heap, default: memory minus 3 GB), ATC_NATIVE_THREADS
# (builder threads, default: all cores), ATC_NATIVE_MARCH (default compatibility).
# Extra native-image arguments are passed through.
set -euo pipefail
ROOT=$(cd "$(dirname "$0")/.." && pwd)

# Physical memory in GiB, rounded (a "16 GB" runner reports 15.6 GiB), for
# Linux, macOS and Git Bash on Windows; 16 when unknown.
memory_gib() {
  local kib bytes
  if [[ -r /proc/meminfo ]]; then
    kib=$(awk '/^MemTotal:/ { print $2 }' /proc/meminfo); echo $(( (kib + 524288) / 1048576 ))
  elif command -v sysctl >/dev/null 2>&1 && bytes=$(sysctl -n hw.memsize 2>/dev/null); then
    echo $(( (bytes + 536870912) / 1073741824 ))
  elif command -v wmic >/dev/null 2>&1; then
    bytes=$(wmic ComputerSystem get TotalPhysicalMemory 2>/dev/null | tr -dc '0-9'); echo $(( (${bytes:-0} + 536870912) / 1073741824 ))
  else
    echo 16
  fi
}

default_heap() {
  local gib; gib=$(memory_gib)
  if (( gib - 3 > 24 )); then echo "24g"
  elif (( gib - 3 >= 8 )); then echo "$(( gib - 3 ))g"
  else echo "8g"
  fi
}
: "${GRAALVM_HOME:?set GRAALVM_HOME to a GraalVM 25.3+ installation}"
DIST="$ROOT/out/dist.dest"
OUT="$ROOT/out/native"
# Builder heap: by default all physical memory but 3 GB (the builder's own
# native memory and the OS), at most 24g, so a bigger machine is used without
# configuration; ATC_NATIVE_XMX overrides (13g on a 16 GB runner is the edge).
XMX="${ATC_NATIVE_XMX:-$(default_heap)}"
# x64 images target the baseline ISA so one binary runs on every x64 machine;
# arm64 images take native-image's default.
MARCH="${ATC_NATIVE_MARCH:-compatibility}"
# Builder threads: fewer threads compile fewer methods at once and need less heap
# (GitHub's runners have 4 cores; 12 GB with 10 threads runs out of memory).
THREADS="${ATC_NATIVE_THREADS:-}"
mkdir -p "$OUT/metadata"
PYTHON=python3; command -v python3 >/dev/null 2>&1 || PYTHON=python
"$PYTHON" "$ROOT/native/sdk-reflection.py" "$DIST/atc.jar" "$OUT/metadata/reachability-metadata.json"
NATIVE_IMAGE="$GRAALVM_HOME/bin/native-image"
[[ -x "$NATIVE_IMAGE" ]] || NATIVE_IMAGE="$GRAALVM_HOME/bin/native-image.cmd" # Windows
# -H:+RuntimeClassLoading   define classes at run time (REPL wrappers, StopRepl); they run interpreted
# -H:+AllowJRTFileSystem    the compiler's JDK classpath (jrt:/ under -Djava.home)
# -H:Preserve               keep every class, method and field agent code may link against: the
#                           agent-facing library jar (atc.lib + the Scala stdlib) and the JDK
#                           packages agent code can reach (the validator blocks java.io/nio/net
#                           and reflection); without it runtime-loaded code dies on the first
#                           member the app itself never used ("Unable to call AOT method").
#                           (Do not add -H:-PreserveIncludesJNI to save memory: the interpreter
#                           then cannot call caller-sensitive methods such as
#                           MethodHandles.lookup, which Scala's lazy vals need.) All of
#                           java.base fits but needs a 20 GB builder heap and 12 minutes.
# -Ob                       quick build (an -O2 image is faster but builds much longer)
# DeadlockWatchdogInterval  a GC-bound phase on a small runner can go 10 minutes without
#                           progress; the default watchdog would abort the build
# native/metadata           reachability metadata from the tracing agent: echo-model runs and
#                           real turns over the OpenAI Responses and chat-completions
#                           adapters (Jackson internals, kotlin-reflect, TLS providers),
#                           REPL wrapper classes removed
# $OUT/metadata             generated by native/sdk-reflection.py: every class of the provider
#                           SDKs registered for reflection with its constructors and
#                           Jackson-annotated members (the SDKs deserialize responses with
#                           Jackson over reflection; the tracing agent only records the
#                           classes of the responses it happened to see)
exec "$NATIVE_IMAGE" \
  "-J-Xmx$XMX" \
  ${THREADS:+--parallelism=$THREADS} \
  -H:DeadlockWatchdogInterval=30 \
  -Ob \
  -march="$MARCH" \
  -H:+UnlockExperimentalVMOptions \
  -H:+RuntimeClassLoading \
  -H:+AllowJRTFileSystem \
  -H:ConfigurationFileDirectories="$ROOT/native/metadata,$OUT/metadata" \
  --enable-native-access=ALL-UNNAMED \
  -H:+ReportExceptionStackTraces \
  "$@" \
  -cp "$DIST/atc-lib.jar" \
  -H:Preserve=path="$DIST/atc-lib.jar",package=java.lang,package=java.lang.invoke,package=java.util,package=java.util.regex,package=java.util.function,package=java.util.stream,package=java.time,package=java.time.format,package=java.time.temporal,package=java.text,package=java.math \
  -jar "$DIST/atc.jar" \
  -o "$OUT/atc"
